#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          12
bspc config focused_border_color "#81A1C1"
bspc config normal_border_color "#4C566A"
bspc config presel_border_color "#81A1C1"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
/home/beltza/.config/autorun.sh
xsetroot -cursor_name left_ptr
killall -q sxhkd
sxhkd
