#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width        4 
bspc config window_gap          5
bspc config focused_border_color "#b16286"
bspc config normal_border_color "#3c3836"
bspc config active_border_color "#3c3836"
bspc config top_padding -3 
bspc config focus_follows_pointer true

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a Emacs state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
picom --experimental-backend &
/home/beltza/.config/bspwm/autorun.sh
xsetroot -cursor_name left_ptr
killall -q sxhkd
sxhkd
